name: Notify Solve Streak

on:
  push:
    paths:
      - '**/*'  # すべてのファイルが対象

jobs:
  notify-solve-streak:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # 過去のコミットも含めて取得（diff用）
  
    - name: Has diff?
      if: github.event.before == '0000000000000000000000000000000000000000'
      run: |
        echo "This is the first commit, skipping diff."
        exit 0

    - name: Get changed files
      run: |
        files=git diff --name-only ${{ github.event.before }} ${{ github.sha }}  | grep -E '^[0-9]+-[A-G]\.$' | sort | uniq
        echo "Changed files: $files"
        echo "files=$files" >> $GITHUB_ENV

    - name: Notify if files are defined
      if: env.files != ''
      run: |
        echo "Changed files are: ${{ env.files }}"
    