name: Notify Solve Streak

on:
  push:
    paths:
      - '**/*'  # すべてのファイルが対象

jobs:
  notify-solve-streak:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # 過去のコミットも含めて取得（diff用）
  
    - name: Get commit info and changed files
      run: |
        echo "Latest commit SHA: ${{ github.sha }}"
        echo "Commit message: ${{ github.event.head_commit.message }}"
        echo "Committed by: ${{ github.event.head_commit.committer.name }}"
        
        echo "Changed files:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }}